# Generated by Django 4.0.4 on 2022-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_childvaccinationdetials_2018_19_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='childdiseasedetials_2017_18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=20)),
                ('Year', models.CharField(max_length=20)),
                ('pneumonia', models.IntegerField()),
                ('astma', models.IntegerField()),
                ('sephesis', models.IntegerField()),
                ('tetanus', models.IntegerField()),
                ('tuberculosis', models.IntegerField()),
            ],
        ),
    ]
