# Generated by Django 4.0.4 on 2022-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_childdiseasedetials_2017_18'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
